import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs" className='dark'>
      <body className={manrope.className }>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
